import json

with open("notebooks/02_preprocessing.ipynb", "r") as f:
    nb = json.load(f)

# Fix cell 14: pipeline.steps -> prep_config.steps
old14 = (
    'from alpr_dataset.preprocessing.pipeline import PreprocessingPipeline\n'
    '\n'
    'pipeline = PreprocessingPipeline(prep_config)\n'
    '\n'
    'print("Pipeline steps (in order):")\n'
    'for i, step in enumerate(pipeline.steps):\n'
    '    s = prep_config.steps[i]\n'
    '    print(f"  {i+1}. {s.name}  enabled={s.enabled}  params={s.params}")\n'
    'print(f"\\nTarget size: {pipeline.target_size}")\n'
)
new14 = (
    'from alpr_dataset.preprocessing.pipeline import PreprocessingPipeline\n'
    '\n'
    'pipeline = PreprocessingPipeline(prep_config)\n'
    '\n'
    'print("Pipeline steps (in order):")\n'
    'for i, step in enumerate(prep_config.steps):\n'
    '    if not step.enabled:\n'
    '        continue\n'
    '    print(f"  {i+1}. {step.name}  enabled={step.enabled}  params={step.params}")\n'
    'print(f"\\nTarget size: {prep_config.target_size}")\n'
)
nb["cells"][14]["source"] = new14.splitlines(keepends=True)

# Fix cell 16: Use STEP_REGISTRY for per-step demo
old16 = (
    'import cv2\n'
    'import numpy as np\n'
    'from alpr_dataset.io_utils import list_images\n'
    '\n'
    '# Find first available image\n'
    'sample_img_path = None\n'
    'for spec in config.datasets:\n'
    '    images = list_images(spec.root)\n'
    '    if images:\n'
    '        sample_img_path = images[0]\n'
    '        break\n'
    '\n'
    'if sample_img_path is None:\n'
    '    raise RuntimeError("No images found in any dataset!")\n'
    '\n'
    'original = safe_read_image(sample_img_path)\n'
    'print(f"Sample: {sample_img_path} \\u2014 shape={original.shape}" if original is not None else "Failed to load")\n'
    '\n'
    '# Apply each enabled step independently\n'
    'fig, axes = plt.subplots(2, 3, figsize=(12, 8))\n'
    'axes[0,0].imshow(bgr_to_rgb(original))\n'
    'axes[0,0].set_title("Original"); axes[0,0].axis("off")\n'
    '\n'
    'current = original.copy()\n'
    'ax_idx = 1\n'
    'seen_names = ["Original"]\n'
    'for step in prep_config.steps:\n'
    '    if not step.enabled or step.name in ("letterbox",):\n'
    '        continue\n'
    '    transformed = pipeline.apply_step(current.copy(), step)\n'
    '    r, c = divmod(ax_idx, 3)\n'
    '    axes[r,c].imshow(bgr_to_rgb(transformed))\n'
    '    axes[r,c].set_title(step.name, fontsize=9); axes[r,c].axis("off")\n'
    '    ax_idx += 1\n'
    '    seen_names.append(step.name)\n'
    '\n'
    'for a in axes.flat[ax_idx:]:\n'
    '    a.axis("off")\n'
    'fig.suptitle(f"Per-step transforms: {sample_img_path.name}", fontsize=12)\n'
    'fig.tight_layout(); plt.show()\n'
)
new16 = (
    'import cv2\n'
    'import numpy as np\n'
    'from alpr_dataset.io_utils import list_images\n'
    '\n'
    '# Find first available image\n'
    'sample_img_path = None\n'
    'for spec in config.datasets:\n'
    '    images = list_images(spec.root)\n'
    '    if images:\n'
    '        sample_img_path = images[0]\n'
    '        break\n'
    '\n'
    'if sample_img_path is None:\n'
    '    raise RuntimeError("No images found in any dataset!")\n'
    '\n'
    'original = safe_read_image(sample_img_path)\n'
    'print(f"Sample: {sample_img_path} \\u2014 shape={original.shape}" if original is not None else "Failed to load")\n'
    '\n'
    '# Apply each enabled step independently using STEP_REGISTRY\n'
    'from alpr_dataset.preprocessing.pipeline import STEP_REGISTRY\n'
    '\n'
    'fig, axes = plt.subplots(2, 3, figsize=(12, 8))\n'
    'axes[0,0].imshow(bgr_to_rgb(original))\n'
    'axes[0,0].set_title("Original"); axes[0,0].axis("off")\n'
    '\n'
    'ax_idx = 1\n'
    'seen_names = ["Original"]\n'
    'for step in prep_config.steps:\n'
    '    if not step.enabled or step.name in ("letterbox",):\n'
    '        continue\n'
    '    fn = STEP_REGISTRY.get(step.name)\n'
    '    if fn is None:\n'
    '        continue\n'
    '    params = dict(step.params)\n'
    '    if step.name in ("resize", "letterbox") and "target_size" not in params:\n'
    '        params["target_size"] = prep_config.target_size\n'
    '    transformed = fn(original.copy(), **params)\n'
    '    r, c = divmod(ax_idx, 3)\n'
    '    axes[r,c].imshow(bgr_to_rgb(transformed))\n'
    '    axes[r,c].set_title(step.name, fontsize=9); axes[r,c].axis("off")\n'
    '    ax_idx += 1\n'
    '    seen_names.append(step.name)\n'
    '\n'
    'for a in axes.flat[ax_idx:]:\n'
    '    a.axis("off")\n'
    'fig.suptitle(f"Per-step transforms: {sample_img_path.name}", fontsize=12)\n'
    'fig.tight_layout(); plt.show()\n'
)
nb["cells"][16]["source"] = new16.splitlines(keepends=True)

# Fix cell 18: pipeline.run -> pipeline.apply
old18 = (
    'rng = random.Random(42)\n'
    'all_images = []\n'
    'for spec in config.datasets:\n'
    '    all_images.extend(list_images(spec.root))\n'
    '\n'
    'sample_paths = rng.sample(all_images, min(6, len(all_images)))\n'
    '\n'
    'fig, axes = plt.subplots(3, 2, figsize=(10, 12))\n'
    'for idx, img_path in enumerate(sample_paths):\n'
    '    img = safe_read_image(img_path)\n'
    '    if img is None:\n'
    '        continue\n'
    '    processed = pipeline.run(img)\n'
    '    \n'
    '    ax = axes.flat[idx]\n'
    '    comparison = np.hstack([img, processed])\n'
    '    ax.imshow(bgr_to_rgb(comparison))\n'
    '    ax.set_title(f"Before (L) / After (R) \\u2014 {img_path.name}", fontsize=8)\n'
    '    ax.axis("off")\n'
    'fig.suptitle("Preprocessing: Before vs After", fontsize=14)\n'
    'fig.tight_layout(); plt.show()\n'
)
new18 = old18.replace("pipeline.run(img)", "pipeline.apply(img)")
nb["cells"][18]["source"] = new18.splitlines(keepends=True)

# Fix cell 20
old20_start = (
    'from tqdm import tqdm\n'
    '\n'
    'processed_root = config.data_processed_dir / "preprocessed"\n'
    '\n'
    'for spec in config.datasets:\n'
    '    images = list_images(spec.root)\n'
    '    print(f"Processing {spec.name} ({len(images)} images)...")\n'
    '    \n'
    '    out_img_dir = processed_root / spec.name / "images"\n'
    '    out_img_dir.mkdir(parents=True, exist_ok=True)\n'
    '    \n'
    '    # Load annotations for YOLO labels\n'
    '    annots = load_dataset_annotations(spec)\n'
    '    out_lbl_dir = processed_root / spec.name / "labels"\n'
    '    out_lbl_dir.mkdir(parents=True, exist_ok=True)\n'
    '    \n'
    '    n_ok = 0\n'
    '    for img_path in tqdm(images, desc=spec.name):\n'
    '        img = safe_read_image(img_path)\n'
    '        if img is None:\n'
    '            continue\n'
    '        processed = pipeline.run(img)\n'
    '        cv2.imencode(".jpg", processed)[1].tofile(str(out_img_dir / img_path.name))\n'
    '        \n'
    '        # Copy YOLO label (harmonized)\n'
    '        label_src = unified_dir / spec.name / f"{img_path.stem}.txt"\n'
    '        if label_src.is_file():\n'
    '            with open(label_src, "r") as f:\n'
    '                label_content = f.read()\n'
    '            with open(out_lbl_dir / f"{img_path.stem}.txt", "w") as f:\n'
    '                f.write(label_content)\n'
    '        n_ok += 1\n'
    '    \n'
    '    print(f"  Written: {n_ok} images + labels to {out_img_dir}")\n'
)
new20 = (
    'from tqdm import tqdm\n'
    'from alpr_dataset.annotations.loader import load_dataset_annotations\n'
    'from alpr_dataset.annotations.writer import convert_to_yolo\n'
    '\n'
    'processed_root = config.data_processed_dir / "preprocessed"\n'
    '\n'
    'for spec in config.datasets:\n'
    '    images = list_images(spec.root)\n'
    '    print(f"Processing {spec.name} ({len(images)} images)...")\n'
    '    \n'
    '    out_img_dir = processed_root / spec.name / "images"\n'
    '    out_img_dir.mkdir(parents=True, exist_ok=True)\n'
    '    \n'
    '    # Load annotations and convert to YOLO\n'
    '    annots = load_dataset_annotations(spec)\n'
    '    out_lbl_dir = processed_root / spec.name / "labels"\n'
    '    out_lbl_dir.mkdir(parents=True, exist_ok=True)\n'
    '    \n'
    '    n_ok = 0\n'
    '    for img_path in tqdm(images, desc=spec.name):\n'
    '        img = safe_read_image(img_path)\n'
    '        if img is None:\n'
    '            continue\n'
    '        processed = pipeline.apply(img)\n'
    '        cv2.imencode(".jpg", processed)[1].tofile(str(out_img_dir / img_path.name))\n'
    '        \n'
    '        # Write YOLO label from harmonized annotations\n'
    '        if img_path.stem in annots:\n'
    '            yolo_lines = convert_to_yolo(annots[img_path.stem], *processed.shape[:2])\n'
    '            with open(out_lbl_dir / f"{img_path.stem}.txt", "w") as f:\n'
    '                f.writelines(yolo_lines)\n'
    '        n_ok += 1\n'
    '    \n'
    '    print(f"  Written: {n_ok} images + labels to {out_img_dir}")\n'
)
nb["cells"][20]["source"] = nb["cells"][20]["source"]
# Check if old20_start exists
src20 = "".join(nb["cells"][20]["source"])
if "pipeline.run(img)" in src20:
    src20 = src20.replace("pipeline.run(img)", "pipeline.apply(img)")
if "unified_dir" in src20:
    # Simplify cell 20
    nb["cells"][20]["source"] = new20.splitlines(keepends=True)
    print("Cell 20 replaced completely")
else:
    nb["cells"][20]["source"] = src20.splitlines(keepends=True)

with open("notebooks/02_preprocessing.ipynb", "w") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)
print("All fixes applied")
